// deno-lint-ignore-file no-explicit-any
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { serve } from "https://deno.land/std@0.224.0/http/server.ts";

/**
 * Supabase Auth Hook: Send SMS via MSG91
 * 
 * This function is called AUTOMATICALLY by Supabase Auth when:
 * - supabase.auth.signInWithOtp({ phone }) is called
 * - Supabase generates OTP internally and sends it here
 * 
 * Configure in Supabase Dashboard:
 * Authentication → Hooks → Send SMS Hook → Set this function URL
 * 
 * Environment Variables Required:
 * - MSG91_KEY: Your MSG91 Auth Key
 * - MSG91_FLOW_TEMPLATE_ID: Your MSG91 Flow Template ID for OTP
 * - HOOK_SECRET: (Optional) Secret to verify Supabase signature
 */

const HOOK_SECRET = Deno.env.get("HOOK_SECRET");
const MSG91_KEY = Deno.env.get("MSG91_KEY");
const MSG91_FLOW_TEMPLATE_ID = Deno.env.get("MSG91_FLOW_TEMPLATE_ID") || Deno.env.get("MSG91_SMSOTP_TEMPLATE_ID");
const MSG91_SMS_ENDPOINT = "https://api.msg91.com/api/v5/flow/";

// Must match your MSG91 template variable name
const MSG91_OTP_VAR_NAME = "otp";

/**
 * Verify Supabase webhook signature (optional but recommended)
 */
async function verifySignature(req: Request): Promise<boolean> {
  if (!HOOK_SECRET) return true; // Skip if no secret configured
  
  const signature = req.headers.get("x-supabase-signature") || "";
  const body = await req.clone().text();
  
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(HOOK_SECRET),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  
  const signed = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(body));
  const digest = btoa(String.fromCharCode(...new Uint8Array(signed)));
  
  return signature === `v1,${digest}`;
}

function json(status: number, data: any) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json" },
  });
}

serve(async (req) => {
  // Verify signature if HOOK_SECRET is set
  // Uncomment this for production:
  // if (HOOK_SECRET && !(await verifySignature(req))) {
  //   return new Response("Invalid signature", { status: 401 });
  // }

  // Check required env vars
  if (!MSG91_KEY || !MSG91_FLOW_TEMPLATE_ID) {
    console.error("Missing MSG91 configuration");
    return json(500, {
      ok: false,
      error: "Missing required MSG91 env vars",
      need: ["MSG91_KEY", "MSG91_FLOW_TEMPLATE_ID"],
    });
  }

  // Parse JSON body
  let body: any;
  try {
    body = await req.json();
  } catch (e) {
    return json(400, {
      ok: false,
      error: "Invalid JSON body",
      details: String(e),
    });
  }

  /**
   * Supabase Auth Hook payload format:
   * {
   *   user: { id, phone: "+919961491824", ... },
   *   sms: { otp: "123456" }
   * }
   * 
   * The phone number includes country code with + prefix
   * The OTP is a 6-digit code generated by Supabase
   * 
   * Also supports manual testing:
   * { to: "+919961491824", otp: "123456" }
   */
  const otp = body?.sms?.otp ?? body?.otp;
  const toInput = body?.user?.phone ?? body?.sms?.to ?? body?.to;

  if (!otp || !toInput) {
    return json(400, {
      ok: false,
      error: "Missing recipient or OTP",
      got: {
        hasUserPhone: !!body?.user?.phone,
        hasSmsOtp: !!body?.sms?.otp,
        hasTo: !!(body?.sms?.to ?? body?.to),
      },
      hint: "Supabase Auth sends { user: { phone }, sms: { otp } }. For manual test: { to, otp }",
    });
  }

  // MSG91 expects countrycode+number, no leading '+'
  const mobile = String(toInput).replace(/^\+/, "");

  console.log("📱 [SEND-SMS-HOOK] Sending OTP to:", mobile);

  // Build MSG91 Flow payload
  const payload = {
    template_id: MSG91_FLOW_TEMPLATE_ID,
    recipients: [
      {
        mobiles: mobile,
        [MSG91_OTP_VAR_NAME]: String(otp),
      },
    ],
  };

  // Send to MSG91
  try {
    const resp = await fetch(MSG91_SMS_ENDPOINT, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "accept": "application/json",
        "authkey": MSG91_KEY,
      },
      body: JSON.stringify(payload),
    });

    const text = await resp.text();
    let data: any = text;
    
    try {
      data = JSON.parse(text);
    } catch {
      // Leave as text if not valid JSON
    }

    if (!resp.ok) {
      console.error("📱 [SEND-SMS-HOOK] MSG91 error:", resp.status, data);
      return json(400, {
        ok: false,
        provider: "msg91",
        status: resp.status,
        response: data,
      });
    }

    console.log("📱 [SEND-SMS-HOOK] SMS sent successfully to:", mobile);
    
    // Success response for Supabase Auth Hook
    return json(200, {
      ok: true,
      provider: "msg91",
      result: data,
    });

  } catch (error) {
    console.error("📱 [SEND-SMS-HOOK] Network error:", error);
    return json(500, {
      ok: false,
      error: "Failed to connect to MSG91",
      details: String(error),
    });
  }
});
